#
# JBZoo - Toolbox
#
# This file is part of the JBZoo project.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @package    Toolbox
# @license    MIT
# @copyright  Copyright (C) JBZoo.com, All rights reserved.
# @link       https://github.com/JBZoo/Toolbox
#

language: php
os: linux
dist: xenial

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly
  - 8.0

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: 8.0

before_script:
  - composer self-update

script:
  - make update   --no-print-directory
  - make test-all --no-print-directory
